### ISSUE TITLE
La nación nueva versión en Opera

### ISSUE THREAD

**Issue by jessicablossom** [wacko/diarios-anonimos#1]
**Browser**: Opera 31.0.18
![2015-09-21_093912](https://cloud.githubusercontent.com/assets/11197367/9991948/ec2494ce-6044-11e5-9881-6aee32e2746b.png)

Dejo de funcionar el plugin cuando actualizaron la versión del sitio.

**Comment by wacko** [comment]
Plugin actualizado y en proceso de revisión

**Comment by wacko** [comment]
Actualizado para Chrome y Opera (v0.0.5)
