### ISSUE TITLE
Ha dejado de funcionar con Clarín. 

### ISSUE THREAD

**Issue by root-phantasoft** [wacko/diarios-anonimos#2]
La Nación aún funciona correctamente. Chrome 54, 64-bits, GNU/Linux.

**Comment by ala747** [comment]
Confirmo.

Cambiaron '.modalLoginPase' por '.modal-pase'.

**Comment by ala747** [comment]
En el PR #3 paso un fix para esto, por si alguien quiere probarlo.

**Comment by wacko** [comment]
Merged!
